### PR TITLE
shellevents: add windowtitlev2 event

### PR DESCRIPTION
**Pull request by andresilva**
## Things done

- For new programs
  - [ ] Add the program to the [README](/README.md) table, with yourself as the
        maintainer
  - [ ] Add a README for the program itself
  - [ ] Add Makefile (and Nix derivation optionally, otherwise @fufexan will do
        it)
  - [ ] If the program is a script, add it to the
        [CI checks matrix](/.github/workflows/check.yml)

- For changes
  - [x] Add changes to the [CHANGELOG](/CHANGELOG.md)

### CODE REVIEW

**Comment by fufexan** [comment]
@trippwill

**Comment by trippwill** [comment]
@fufexan looks good to me.

I'm not currently an active user of Hyprland, and this contrib seems to be getting some use. Could you find a new, more active, maintaner?

**Comment by fufexan** [comment]
Sure, I'll open an issue requesting a maintainer.

**Review by fufexan — COMMENTED** [review]
Can you also mention this addition in the changelog?

**Comment by andresilva** [comment]
@fufexan updated the changelog

**Review by fufexan — APPROVED** [review]
LGTM

**Pull request merged**
