### PR TITLE
Monitor Script.

### PR DESCRIPTION
**Pull request by niksingh710**
Simple Script is written in python3 That is using hyprctl to give the next monitor so that the user can cycle between these monitors easily.

### CODE REVIEW

**Comment by fufexan** [comment]
2 of the 3 functionalities of this script can be achieved with
```ini
  # cycle monitors
  bind = SUPERSHIFT, braceleft, focusmonitor, l
  bind = SUPERSHIFT, braceright, focusmonitor, r
```

**Comment by niksingh710** [comment]
> 2 of the 3 functionalities of this script can be achieved with
> 
> ```ini
>   # cycle monitors
>   bind = SUPERSHIFT, braceleft, focusmonitor, l
>   bind = SUPERSHIFT, braceright, focusmonitor, r
> ```

yes doing that is possible but using one single shortcut to perform these actions make it feel seemless.

**Comment by niksingh710** [comment]
> ```ini
>   bind = SUPERSHIFT, braceleft, focusmonitor, l
> ```

what is `braceleft` is this a keyword or a dispatcher?

**Comment by vaxerski** [comment]
it's a key bruh

**Comment by niksingh710** [comment]
> it's a key bruh

Aah i guessed so.

This needs two key maps to cycle between monitors
That's why I wrote this script to perform that in one key press.

**Comment by edrex** [comment]
monitor relative positioning `+1` wraps around, allowing to cycle.

**Comment by niksingh710** [comment]
bad

**Pull request closed without merging**
