### PR TITLE
Add hyprprop

### PR DESCRIPTION
**Pull request by Douile**
Adds hyprprop, a xprop replacement for hyprland, it allows you to select a window to view its properties from hyprctl.

Useful for getting information for window rules and checking if things are using xwayland.

hyprprop

### CODE REVIEW

**Comment by vaxerski** [comment]
@fufexan

**Comment by fufexan** [comment]
I think we could use the pretty print (non-json) by default, and print json when a flag is set (e.g. `-j | --json`).

**Comment by Douile** [comment]
> I think we could use the pretty print (non-json) by default, and print json when a flag is set (e.g. `-j | --json`).

As in reformat the output so it looks like `hyprctl clients`?

**Comment by fufexan** [comment]
Yes. Though now that I think about it, we don't need to overcomplicate over a stylistic change. Pretty printed json is more than enough.

**Comment by fufexan** [comment]
Thanks for your contribution!

**Pull request merged**
